"""Native spam detection for cargo360 — bulk/marketing/newsletter heuristics.

Independent of phishing: an email can be spam (unwanted bulk) without being a
phishing threat. Uses ONLY data cargo360 already stores (subject, from, body);
no dependency on the upstream parser-email-op spam_score.
"""
import re
from typing import Dict, Any, List, Tuple, Optional

# Bulk/automated sender local-parts
BULK_SENDER = re.compile(
    r'^(noreply|no-reply|newsletter|news|marketing|promo|promotii|mailer|mailing|'
    r'campaign|campanii|notifications?|notificari|bulletin|hello|noreply\d*|'
    r'savings|promotions|deals|offers|updates|team)@',
    re.IGNORECASE)

# Unsubscribe / list-management language (strongest native bulk signal)
UNSUB = re.compile(
    r'(unsubscribe|dezabon|dez-abon|opt[\s-]?out|nu mai (doresc|doriti|vrei) sa prim|'
    r'renunta la abonare|gestioneaza preferintele|email preferences|update your preferences)',
    re.IGNORECASE)

VIEW_BROWSER = re.compile(
    r'(view (this email )?in (your )?browser|vizualiza(ti)? (in|din) browser|'
    r'vezi in browser|see it in your browser)', re.IGNORECASE)

# Auto-reply / automated message disclaimer
AUTOREPLY_DISCLAIMER = re.compile(
    r'(this is an automated (message|email|notification)|'
    r'do not reply to this (email|message)|'
    r'this email was sent automatically|'
    r'acest mesaj a fost generat automat|'
    r'nu (raspunde|răspunde) la acest (email|mesaj))',
    re.IGNORECASE)

# Newsletter / promotional subscription language (EN)
NEWSLETTER_EN = re.compile(
    r'(you (are|\'re) receiving this( email)? because|'
    r'you signed up for|'
    r'manage your email preferences|'
    r'update your preferences|'
    r'click here to unsubscribe)',
    re.IGNORECASE)

# Travel / hospitality promotional content
TRAVEL_PROMO = re.compile(
    r'(hotels (travelers|travellers) love|'
    r'\bbook now\b|'
    r'find a deal|'
    r'exclusive deal|'
    r'save up to \d|'
    r'\bfree ride\b|'
    r'your next trip|'
    r'plan your trip)',
    re.IGNORECASE)

# Marketing / promotional vocabulary
MARKETING = re.compile(
    r'(\b\d{1,3}\s?% ?(reducere|off|discount)|reducere|discount|oferta|oferte|promot|'
    r'\bsale\b|black friday|cyber monday|voucher|cupon|\bgratuit\b|castiga|premiu|webinar|'
    r'abonea?z|newsletter|early access|limited time|ultima sansa|doar azi|exclusiv pentru tine)',
    re.IGNORECASE)

DEFAULT_SPAM_THRESHOLD = 50

# ── Auto-generated / no-reply detection (personal mailboxes only) ──────────────

_AUTOGEN_FROM = re.compile(
    r'^(noreply|no-reply|donotreply|do-not-reply|auto-reply|autoreply|'
    r'notifications?|alerting|no\.reply)@',
    re.IGNORECASE)

_AUTOGEN_SUBJECT = re.compile(
    r'(auto.?generated|automatic\s+reply|auto\s*reply|autoreply|'
    r'do\s+not\s+reply|no.?reply|out\s+of\s+office|away\s+from\s+office)',
    re.IGNORECASE)

_AUTOGEN_BODY = re.compile(
    r'(this\s+is\s+an?\s+auto.?generated\s+(message|email|response)|'
    r'please\s+do\s+not\s+reply(\s+to\s+this\s+email)?|'
    r'auto.?generated\s+(message|email|notification)|'
    r'do\s+not\s+reply\s+to\s+this\s+(email|message))',
    re.IGNORECASE)


def detect_autogenerated(
    email: Dict[str, Any],
    extra_headers: Optional[Dict[str, str]] = None,
) -> Tuple[float, List[Dict[str, Any]]]:
    """Detect auto-generated / no-reply messages (ticketing, corporate autoreply, system notifications).

    Returns (score, reasons). Score 60 when triggered — above SPAM_THRESHOLD.
    Intended only for personal mailbox pipeline; does not affect CTS pipeline.
    extra_headers: dict with lowercased header names from IMAP fetch
                   (e.g. {'auto-submitted': 'auto-generated', 'x-auto-response-suppress': '...'}).
    """
    reasons: List[Dict[str, Any]] = []
    frm = email.get('from_address') or ''
    subject = email.get('subject') or ''
    body = (email.get('body_text') or '') + ' ' + (email.get('body_html') or '')
    hdrs = extra_headers or {}

    def add(code: str, weight: int, text: str):
        reasons.append({'code': code, 'weight': weight, 'match_text': str(text)[:120]})

    # Header: Auto-Submitted (RFC 3834) — auto-replied / auto-generated / auto-notified
    auto_submitted = hdrs.get('auto-submitted', '')
    if auto_submitted and auto_submitted.lower() not in ('no', ''):
        add('autogen_header_auto_submitted', 60, auto_submitted)
        return 60.0, reasons

    # Header: X-Auto-Response-Suppress — Exchange/O365 suppression flag
    if 'x-auto-response-suppress' in hdrs:
        add('autogen_header_x_auto_response_suppress', 60, hdrs['x-auto-response-suppress'])
        return 60.0, reasons

    # From address pattern (strong signal — dedicated no-reply address)
    if _AUTOGEN_FROM.match(frm):
        add('autogen_from_noreply', 35, frm)

    # Subject pattern
    m = _AUTOGEN_SUBJECT.search(subject)
    if m:
        add('autogen_subject_pattern', 35, m.group(0))

    # Body phrases — each distinct match adds weight independently (cap at 2)
    seen_body = set()
    for m in _AUTOGEN_BODY.finditer(body):
        key = m.group(0).lower()[:40]
        if key not in seen_body:
            seen_body.add(key)
            add('autogen_body_phrase', 35, m.group(0))
            if len(seen_body) >= 2:
                break

    score = min(sum(r['weight'] for r in reasons), 100)
    return float(score), reasons


def detect_spam(email: Dict[str, Any]) -> Tuple[float, List[Dict[str, Any]]]:
    """Return (spam_score 0-100, reasons[]). Pure: no DB, no network."""
    reasons: List[Dict[str, Any]] = []
    frm = email.get('from_address') or ''
    subject = email.get('subject') or ''
    # Spam-ul se evalueaza DOAR pe continutul NOU scris de expeditor, nu pe istoricul citat. Cheia e
    # ca tratam diferit REPLY-urile de mailurile noi (vezi 12621 vs 12619):
    #  - REPLY/FWD: subiectul e MOSTENIT (ex. "RE: Oferta...CargoTrack" = oferta NOASTRA) si HTML-ul
    #    citat scurge promotia noastra (quote-stripping-ul pe HTML e nesigur). Deci scanam DOAR TEXTUL
    #    nou (quote-strip fiabil) — raspunsul benign al clientului ("suna-ma") nu mai e marcat spam.
    #  - MAIL NOU (fara prefix): subiect + text + HTML — newsletter-ele bulk isi tin 'unsubscribe'/
    #    'oferta' in HTML, iar partea text e doar un teaser; trebuie scanat tot ca sa le prindem.
    try:
        from app.services import phishing_detector
        _nt, _nh, _ = phishing_detector._new_content(email)
    except Exception:
        _nt, _nh = email.get('body_text') or '', email.get('body_html') or ''
    _is_reply = bool(re.match(r'\s*(re|fwd|fw|raspuns|r[ăa]spuns)\s*:', subject, re.IGNORECASE))
    if _is_reply:
        combined = (_nt or '')
    else:
        combined = subject + ' ' + (_nt or '') + ' ' + (_nh or '')

    def add(code, weight, text):
        reasons.append({'code': code, 'weight': weight, 'match_text': str(text)[:120]})

    # Reponderare (2026-06-22) pentru a NU mai marca spam mailul transacțional/notificare legitim.
    # „Link de dezabonare" + „Vizualizare în browser" / „Expeditor automat" sunt prezente ȘI pe
    # newslettere REALE, ȘI pe notificări legitime (feedback, facturi, confirmări). Doar semnalele
    # de bulk NU mai sunt suficiente pentru spam (prag 50): e nevoie de INTENȚIE de marketing,
    # SAU de 3+ semnale de bulk cumulate. Exemple corectate:
    #   dezabonare(25)+view_browser(15)=40  -> NU spam (27015/27009)
    #   dezabonare(25)+expeditor_automat(15)=40 -> NU spam (27597)
    #   dezabonare(25)+marketing(35)=60     -> spam (promo real)
    #   expeditor_automat(15)+marketing(35)=50 -> spam (newsletter promoțional)
    m = UNSUB.search(combined)
    if m:
        add('unsubscribe_link', 25, m.group(0))
    m = VIEW_BROWSER.search(combined)
    if m:
        add('view_in_browser', 15, m.group(0))
    if BULK_SENDER.match(frm):
        add('bulk_sender', 15, frm)
    m = MARKETING.search(combined)
    if m:
        add('marketing_language', 35, m.group(0))
    m = AUTOREPLY_DISCLAIMER.search(combined)
    if m:
        add('autoreply_disclaimer', 20, m.group(0))
    m = NEWSLETTER_EN.search(combined)
    if m:
        add('newsletter_en', 25, m.group(0))
    m = TRAVEL_PROMO.search(combined)
    if m:
        add('travel_promo', 30, m.group(0))

    score = min(sum(r['weight'] for r in reasons), 100)
    return float(score), reasons


def sender_scopes(from_address: str):
    """(adresa_normalizata, [domenii candidate]) pentru cautarea in liste.

    Domeniile includ domeniul expeditorului SI toate domeniile-parinte cu cel putin doua
    etichete: `info@email.akcenta.eu` -> ['email.akcenta.eu', 'akcenta.eu']. Motiv: o regula
    pe `akcenta.eu` trebuie sa prinda si subdomeniile de trimitere (`email.`, `mailing.` etc.),
    exact ca la potrivirea de domenii din redirectul VATHUB. Ultima eticheta singura ('eu',
    'ro', 'com') e EXCLUSA deliberat — o intrare pe un TLD ar bloca/exempta tot traficul.

    Ordinea listei e de la cel mai specific la cel mai general (folosita ca precedenta).
    """
    addr = (from_address or '').lower().strip()
    domain = addr.split('@', 1)[-1] if '@' in addr else ''
    doms = []
    if domain:
        parts = [p for p in domain.split('.') if p]
        for i in range(0, max(len(parts) - 1, 0)):
            doms.append('.'.join(parts[i:]))
    return addr, doms


def _list_hit(addr: str, doms, keys) -> bool:
    """Adresa sau unul dintre domeniile ei (cu parinti) e in setul de chei normalizate."""
    if not keys:
        return False
    if addr and addr in keys:
        return True
    return any(d in keys for d in doms)


def get_sender_reputation(from_address: str, db) -> Optional[str]:
    """Returnează 'allowlist' | 'blocklist' | None.

    Precedență: adresa exactă > domeniul cel mai specific > domenii-părinte (vezi
    `sender_scopes`). Un expeditor specific poate fi allowlist chiar dacă domeniul e pe
    blocklist și invers. Comparația e case-insensitive pe AMBELE părți — intrările salvate
    cu majuscule trebuie să se potrivească la fel.
    """
    from sqlalchemy import text
    addr, doms = sender_scopes(from_address)
    if not addr:
        return None
    row = db.execute(text("""
        SELECT reputation FROM spam_sender_reputation
        WHERE (scope_type='sender_exact' AND lower(scope_value)=:addr)
           OR (scope_type='domain' AND lower(scope_value) = ANY(CAST(:doms AS text[])))
        ORDER BY CASE scope_type WHEN 'sender_exact' THEN 0 ELSE 1 END,
                 length(scope_value) DESC
        LIMIT 1
    """), {"addr": addr, "doms": doms or ['']}).fetchone()
    return row[0] if row else None


def get_sender_reputation_pg(from_address: str, cur) -> Optional[str]:
    """Varianta psycopg2 a get_sender_reputation pentru pipeline-ul de procesare.

    Aceeasi semantica: adresa exacta > domeniu specific > domenii-parinte (`sender_scopes`),
    case-insensitive pe ambele parti. Functioneaza cu cursor normal SAU RealDictCursor.
    """
    addr, doms = sender_scopes(from_address)
    if not addr:
        return None
    cur.execute(
        "SELECT reputation FROM spam_sender_reputation "
        "WHERE (scope_type='sender_exact' AND lower(scope_value)=%s) "
        "   OR (scope_type='domain' AND lower(scope_value) = ANY(CAST(%s AS text[]))) "
        "ORDER BY CASE scope_type WHEN 'sender_exact' THEN 0 ELSE 1 END, "
        "         length(scope_value) DESC LIMIT 1",
        (addr, doms or ['']))
    row = cur.fetchone()
    if not row:
        return None
    return row['reputation'] if isinstance(row, dict) else row[0]


def detect_spam_with_reputation(
    email: Dict[str, Any], db
) -> Tuple[float, List[Dict[str, Any]]]:
    """detect_spam() cu override de reputație din DB.

    - allowlist → score=0, bypass complet (indiferent de semnalele de bulk)
    - blocklist → boost +40 la scorul calculat
    - None → comportament standard detect_spam()
    """
    rep = get_sender_reputation(email.get('from_address'), db)
    if rep == 'allowlist':
        return 0.0, [{'code': 'allowlist_bypass', 'weight': 0, 'match_text': ''}]
    score, reasons = detect_spam(email)
    if rep == 'blocklist':
        score = min(score + 40, 100)
        reasons.append({'code': 'blocklist_boost', 'weight': 40, 'match_text': ''})
    return score, reasons


def sender_gate_verdict(email: Dict[str, Any], reputation: Optional[str] = None,
                        manual_whitelist: Optional[set] = None,
                        manual_spamlist: Optional[set] = None) -> Optional[bool]:
    """Verdictul pe EXPEDITOR, fara scoring de continut: False=exceptat, True=blocat, None=neutru.

    Aceeasi precedenta ca `classify_spam_gate` (whitelist/allowlist bate blocklist/spamlist),
    dar nu ruleaza `detect_spam`. Folosita de gate-urile care ies DEVREME din `process_one`
    (ex. „Automat"), ca un expeditor blocat sa nu poata ocoli oprirea ca spam.
    """
    saddr, sdoms = sender_scopes(email.get('from_address'))
    if reputation == 'allowlist' or _list_hit(saddr, sdoms, manual_whitelist or set()):
        return False
    if reputation == 'blocklist' or _list_hit(saddr, sdoms, manual_spamlist or set()):
        return True
    return None


def classify_spam_gate(email: Dict[str, Any], reputation: Optional[str] = None,
                       manual_whitelist: Optional[set] = None,
                       manual_spamlist: Optional[set] = None
                       ) -> Tuple[float, List[Dict[str, Any]], Optional[bool]]:
    """Clasificare spam APLICÂND poarta de liste expeditori. Pură (fără DB/rețea).

    SURSĂ UNICĂ de adevăr pentru decizia de spam — folosită identic de pipeline-ul live
    (`process_email.process_one`) și de recalcularea în masă (`/spam/backfill`), ca să nu
    poată diverge (driftul a fost cauza unui bug anterior).

    Returnează (spam_score, reasons, override) cu override ∈ {False, True, None}:
      False -> NU spam (allowlist SAU whitelist manuală pe EXPEDITOR);
      True  -> spam forțat (blocklist reputație SAU blacklist tip=spam);
      None  -> fără override — scorul + pragul decid; păstrează deciziile manuale existente.
    Precedență: whitelist/allowlist BATE blocklist/spamlist (whitelist ⇒ niciodată spam).

    Whitelist-ul se aplică DOAR pe EXPEDITORUL real (from_address sau domeniul lui) — NU pe adrese
    care apar în corpul/thread-ul mailului. Motiv: dacă pe o adresă a noastră (ex. office@) intră
    spam trimis de terți, trebuie marcat spam; doar mailurile TRIMISE DE LA o adresă whitelist sunt
    scutite. Cazul „reply de client care citează oferta noastră" e rezolvat de detect_spam, care
    scanează doar mesajul nou (promoția citată nu declanșează semnale). `manual_whitelist` /
    `manual_spamlist`: chei normalizate (email complet sau domeniu bare), ca în settings.
    """
    manual_whitelist = manual_whitelist or set()
    manual_spamlist = manual_spamlist or set()
    saddr, sdoms = sender_scopes(email.get('from_address'))
    sdom = sdoms[0] if sdoms else ''

    # 1) Whitelist (bate tot) — DOAR pe expeditorul real (adresă sau domeniu, cu subdomenii).
    in_whitelist = _list_hit(saddr, sdoms, manual_whitelist)
    if reputation == 'allowlist' or in_whitelist:
        wl_code = 'manual_whitelist_bypass' if in_whitelist else 'allowlist_bypass'
        return 0.0, [{'code': wl_code, 'weight': 0, 'match_text': saddr or sdom or ''}], False

    # 2) Scoring pe conținut (detect_spam scanează doar mesajul nou, fără istoricul citat).
    score, reasons = detect_spam(email)

    # 3) Blocklist reputație SAU blacklist manuală tip=spam → forțează spam.
    in_spamlist = _list_hit(saddr, sdoms, manual_spamlist)
    if reputation == 'blocklist' or in_spamlist:
        bcode = 'blocklist_sender' if reputation == 'blocklist' else 'manual_blacklist_spam'
        return float(score), list(reasons) + [
            {'code': bcode, 'weight': 0, 'match_text': saddr or sdom}], True

    # 4) Nimic din liste → scorul decide; nu atingem override (păstrăm decizii manuale).
    return float(score), reasons, None
